### ISSUE TITLE
Finish PR 5500 initiative signature gauge

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/dev#36]
We've started the PR with Codegram but didn't manage to finish it properly.
Here is a [comment on the PR](https://github.com/decidim/decidim/pull/5500#issuecomment-631332176) with the remaining tasks.

The idea is to make a PR on [this branch](https://github.com/decidim/decidim/tree/initiatives-signature-gauge) with the remaining changes.

**Comment by ace** [comment]
Hi @virgile-dev. I think I need a bit more detail about the remaining tasks.

- Check that events issued from initiatives are working properly. Are there any specifics about what to check or which events may be affected?

- Check that the edge cases defined here work well. As far as I understand the linked doc, the main issue is having scopes below the level of detail in the authorization. In that case the signature is applied to all child scopes since we can't identify a specific one. Is that right?

- Display a warning in the admin if an initiative does not have a global scope and only global scope config flag is activated on the initiative type. Not sure I understand this use case. I mean, is it possible to get to that situation? If that flag is activated, is it possible to create an initiative without a global scope? Maybe we should enforce that? Do you have a sample of how to display the warning?

- Fix the initiative admin form when the scope is global. What's the issue there? Any kind of process error or just a visual fix?

- Apply design in mockup for signature gauges. Is this related to the bottom margin issue you mentioned in that PR or is there anything else to be done? Not sure how the 'see all' link (mentioned in https://github.com/OpenSourcePolitics/dev/issues/9) should work. Does it 'unfold' the rest of the data or is it a link to a separate page (which one?).

Thanks!

**Comment by virgile-dev** [comment]
Hello @ace 
Here are my answers : 

> Check that events issued from initiatives are working properly. Are there any specifics about what to check or which events may be affected?

* Milestone events are the one that we need to adapt (see [this PR](https://github.com/decidim/decidim/pull/6098) if you don't know what I'm talking about)
* We’d like to send notifications for child scope milestones too (same percentages : 25, 50, 75 and 100%). Notifications would go to authors, promotting committee, followers for all the milestones (25, 50, 75 and 100%). Admins should receive a notification only upon reaching 100%.

> Check that the edge cases defined here work well. As far as I understand the linked doc, the main issue is having scopes below the level of detail in the authorization. In that case the signature is applied to all child scopes since we can't identify a specific one. Is that right? 

* yeah and I think it’s taken care of already 

> Display a warning in the admin if an initiative does not have a global scope and only global scope config flag is activated on the initiative type. Not sure I understand this use case. I mean, is it possible to get to that situation? If that flag is activated, is it possible to create an initiative without a global scope? Maybe we should enforce that? Do you have a sample of how to display the warning? 

* I’m guessing this is more of compatibility issue. If there were already initiatives and you activate the global scope only flag what happens. IMO if you created an initiative with the child scope only the child scope gauge should be display. When it has a global scope then you display the child scope jauge if « child scope signature » flag is enabled.  

> Fix the initiative admin form when the scope is global. What's the issue there? Any kind of process error or just a visual fix? 

* This is more a bad UX thing. The default value when creating a new scope on the initiative type is the global scope. When you click on the scope selector it is thus already selected and you can’t click on « select » you have to close the modal. Here is a screen capture of this behaviour

![scope global](https://user-images.githubusercontent.com/11473995/82691013-8544ed80-9c5d-11ea-8b0a-13b45dd4f696.gif)

> Apply design in mockup for signature gauges. Is this related to the bottom margin issue you mentioned in that PR or is there anything else to be done? Not sure how the 'see all' link (mentioned in #9) should work. Does it 'unfold' the rest of the data or is it a link to a separate page (which one?).

* we won’t take care of this in this first draft

**Comment by ace** [comment]
Thanks @virgile-dev 
Just one thing, do you have any example of how that warning in the admin should look like?

**Comment by virgile-dev** [comment]
@ace which warning are we talking about ? 
This one ? I'm not even sure it needs a warning as it should be compatible. Don't you.
> I’m guessing this is more of compatibility issue. If there were already initiatives and you activate the global scope only flag what happens. IMO if you created an initiative with the child scope only the child scope gauge should be display. When it has a global scope then you display the child scope jauge if « child scope signature » flag is enabled.  

Warning display the same on the front end and in the back end.
<img width="1239" alt="Capture d’écran 2020-05-25 à 15 33 48" src="https://user-images.githubusercontent.com/11473995/82817383-31c0e280-9e9d-11ea-85d0-cce30fb3eea0.png">

**Comment by ace** [comment]
Yes, that one. Not sure if it's needed, to be honest. If it is OK to be in such a state, does the warning provide any help or anything to the admin? I tend to think it does not, so maybe it is not needed at all. So, if you are OK with that, I'll leave it for now.

**Comment by virgile-dev** [comment]
I'm ok with no warning at all @ace

**Comment by ace** [comment]
I'll be keeping Issues I find and whether I've fixed them in this comment, so they can be checked quickly.

[x] Migrations fail (code updating the existing votes is wrong)
[x] Admin editing initiative with offline votes crashes, I18n translation issue (using scope as interpolation key)
[x] Offline votes saved from admin form as string arrays instead of integers and with no total. Example:
`online_votes => {"1"=>1, "total"=>1}; offline_votes => {"1"=>["15"], "2"=>["6"], "4"=>["4"]}`
[x] Required votes just adds up all the scopes required votes. For a parent (1000 votes required) and two children (500 votes required each), that means 2000 votes are needed, with no further check on where they apply.
[x] Total votes just adds up all votes for all scopes. For a parent (1000 votes) and two children (600 and 400 votes), the total is 2000, again, with no check on where they apply. (Note that the two examples will result in an accepted initiative, 2000 = 2000, even though one child is not fulfilled).
[x] Breaks sorting by signatures count in the admin
[x] Sorting by signatures count fail when nils (almost always?)
[x] Migrations fail because one of them removes a column that is used in a later migration

**Comment by ace** [comment]
@virgile-dev while I write the doubts we talked about (seeing some code that clarifies some of them), one more thing I'd need to clarify.

>     * We’d like to send notifications for child scope milestones too (same percentages : 25, 50, 75 and 100%). Notifications would go to authors, promotting committee, followers for all the milestones (25, 50, 75 and 100%). Admins should receive a notification only upon reaching 100%.

This is the content we are sending right now for those milestones for the author and others:
```
        milestone_completed:
          affected_user:
            email_intro: Your initiative %{resource_title} has achieved the %{percentage}% of signatures!
            email_outro: You have received this notification because you are the author of the initiative %{resource_title}.
            email_subject: New milestone completed!
            notification_title: Your <a href="%{resource_path}">%{resource_title}</a> initiative has achieved the %{percentage}% of signatures.
          follower:
            email_intro: The initiative %{resource_title} has achieved the %{percentage}% of signatures!
            email_outro: You have received this notification because you are following %{resource_title}. You can stop receiving notifications following the previous link.
            email_subject: New milestone completed!
            notification_title: The <a href="%{resource_path}">%{resource_title}</a> initiative has achieved the %{percentage}% of signatures.
```
How should we adapt those texts for the child scopes? Keeping them unique may lead to confusions. Same question for the admin messages for 100% in the other PR (https://github.com/decidim/decidim/pull/6098/files#diff-76dc41a8aba2e3fa43b6dfee29b71177). 

One other thing to give a thought, not needed for now. With the process as it is now, we send a 100% milestone notification (and admin notification) for the parent scope when that scope gets enough votes, but that doesn't guarantee that the initiative is completed, because it may lack votes in child scopes. Maybe that will be confusing for the users. In fact all percentages for the parent scope may be missleading.
